# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://FabregasZhou.github.io/homepage
date_format: "ordinal"
title: 呆瓜日志
subtitle: "一个没事码代码的IC工程师"
description: "Xuetong Zhou's blog"
keywords: Xuetong Zhou, Blog
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
